### ISSUE TITLE
spread deploy doesn't work with non default kubectl contexts

### ISSUE THREAD

**Issue by ethernetdan** [redspread/spread#54]
```bash
$ spread deploy . nondefaultcontext

Deploying 3 objects using the context 'nondefaultcontext'.
Deployment found. Did not deploy.: could not get 'default/redspread-registry' (ReplicationController): Get http://localhost:8080/api/v1/namespaces/default/replicationcontrollers/redspread-registry?export=true: dial tcp [::1]:8080: getsockopt: connection refused
```

Expected behavior is to use the context or return an error if the context doesn't exist.

**Comment by jbowen93** [comment]
I also experienced this issue when using [kube-solo](https://github.com/TheNewNormal/kube-solo-osx) for my local cluster. A quick workaround is to run `kube config view > ~/.kube/config`. That got me past the deployment found error. 

Please note that this command will wipe whatever is in your current `~/.kube/config` file. It works for me since my setup doesn't usually use that file.
